
services:

    gw.logger:
        class: Necktie\GatewayBundle\Logger\Logger
        arguments:
          - "@doctrine.orm.entity_manager"


    gw.client_factory:
        class: Necktie\GatewayBundle\Gateway\ClientFactory


    gw.api:
      class: Necktie\GatewayBundle\Gateway\ApiGateway
      arguments:
          - "@gw.client_factory"


    gw.consumer:
        class: Necktie\GatewayBundle\Consumer\GatewayConsumer
        arguments:
          - "@gw.proxy.consumer"


    gw.producer:
        class: Necktie\GatewayBundle\Producer\NecktieProducer


    payment.producer:
        class: Necktie\GatewayBundle\Producer\PaymentProducer


    ### proxy
    gw.proxy.producer:
        class: Necktie\GatewayBundle\Proxy\ProducerProxy
        arguments:
          - "@kernel"


    gw.proxy.consumer:
        class: Necktie\GatewayBundle\Proxy\ConsumerProxy
        arguments:
          - "@event_dispatcher"


    gw.message.logger:
      class: Necktie\GatewayBundle\Message\MessagesLogger
      arguments:
        - "@doctrine.orm.entity_manager"


    gw.message.processor:
        class:  Necktie\GatewayBundle\Message\MessageProcessor
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gw.api"
            - "@gw.logger"
            - "@gw.proxy.producer"
        calls:
            - [ addProcessor, ['@gw.processor.http'] ]
            - [ addProcessor, ['@gw.processor.aweber'] ]


    gw.message.listener:
        class: Necktie\GatewayBundle\EventListener\MessagesListener
        arguments:
          - "@gw.message.logger"
          - "@gw.message.processor"
        tags:
            - { name: kernel.event_listener, event: message.consume, priority: 10 }


    gw.processor.http:
      class: Necktie\GatewayBundle\Gateway\RequestProcessor\HTTPProcessor
      arguments:
        - "@gw.api"
        - "@gw.logger"


    gw.processor.aweber:
      class: Necktie\GatewayBundle\Gateway\RequestProcessor\AWeberProcessor
      arguments:
        - "@gw.logger"

    gw.rabbitmq.reader:
        class: Necktie\GatewayBundle\Services\RabbitReader
        arguments:
              - "%rabbit_url%"
              - "%rabbit_manager_port%"
              - "%rabbit_user%"
              - "%rabbit_password%"


