version: '2'

services:

  php_fpm:
    restart: always
    build:
      context: .
      dockerfile: docker/phpFpm/nuc/Dockerfile
    links:
      - mysql:mysql
    ports:
      #php-fpm
      - "9091:9090"
      #supervisor
      - "9005:9005"
    expose:
      - "9005"
    volumes:
      - .:/var/app

  nginx:
    restart: always
    image: modpreneur/necktie-nginx:0.4
    ports:
        - 9080:80
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx

  mysql:
    restart: always
    extends:
      file: docker-compose.yml
      service: mysql