web_gateway:
  build: .
  ports:
    - "9608:9608"
    - "9001:9001"
    - "8666:8666"
  expose:
    - "9608"
    - "9001"
    - "8666"
  volumes:
    - .:/var/app
#  environment:
#      XDEBUG_CONFIG: remote_host=10.0.1.16






