gateway:
  build: .
  dockerfile: docker/dev/Dockerfile
  ports:
    - "9608:9608"
    - "9005:9002"
    - "8666:8666"
    - "9080:80"
  expose:
    - "9608"
    - "9005"
    - "8666"
    - "9080"
  volumes:
    - .:/var/app
  links:
    - mysql_database:mysql_database


mysql_database:
    image: mysql
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_DATABASE=gateway
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass

