version: '2'
services:

  php_fpm:
    image: modpreneur/necktie-fpm-test:0.10.1
    links:
      - mysql:mysql
    ports:
      #php-fpm
      - "9091:9090"
      #supervisor
      - "9005:9005"
    expose:
      - 9005
    volumes:
      - .:/var/app
    external_links:
      - necktietests_rabbit_mq_1:rabbit_mq

  gw_nginx:
    image: modpreneur/necktie-nginx:0.3
    ports:
        - 9080:80
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql

networks:
  default:
    external:
      name: necktietests_default