version: '2.0'
services:

  php_fpm:
    build:
      context: .
      dockerfile: docker/phpFpm/dev/Dockerfile
    env_file: docker/.env
    links:
#      - mysql:mysql
    ports:
      #php-fpm
      - "9091:9090"
      #supervisor
      - "9005:9005"
    expose:
      - "9005"
    volumes:
      - .:/var/app
    external_links:
      - necktie_rabbit_mq_1:rabbit_mq
      - necktie_nginx_1:necktie

  gw_nginx:
    image: modpreneur/necktie-nginx-dev:0.4
    ports:
        - 9080:80
    links:
        - php_fpm
    volumes_from:
        - php_fpm
    volumes:
      - ./logs/nginx/:/var/log/nginx


#  mysql:
#    image: mysql/mysql-server:5.7
#    ports:
#      - "3307:3306"
#    expose:
#      - "3307"
#    environment:
#      - MYSQL_DATABASE=gateway
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=pass
#      - MYSQL_ROOT_PASSWORD=pass

networks:
  default:
    external:
      name: necktie_default
