version: '2'

services:

  php_fpm:
    build:
      context: .
      dockerfile: docker/phpFpm/dev/Dockerfile
    env_file: docker/.env
    links:
#      - mysql:mysql
      - mysql:database
    ports:
      #php-fpm
      - "9091:9090"
      #supervisor
      - "9005:9002"
    expose:
      - "9005"
    volumes:
      - .:/var/app
      - /Volumes/RAM_Disk:/var/app/var/cache
    environment:
      - GLOB_RUN_NPM=true


  nginx:
        image: modpreneur/necktie-nginx-dev:0.4
        ports:
            - 8889:80
        links:
            - php_fpm
        volumes_from:
            - php_fpm
        volumes:
          - ./logs/nginx/:/var/log/nginx

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql

