imports:
   - { resource: parameters.yml }

framework:
    secret: S0ME_SECRET
    templating:
            engines: ['twig']

    router:
        resource: "%kernel.root_dir%/config/routing.yml"

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
    orm:
        auto_mapping: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

services:


