imports:
   - { resource: parameters.yml }

framework:
    secret: S0ME_SECRET
    templating:
            engines: ['twig']

    router:
        resource: "%kernel.root_dir%/config/routing.yml"

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
    orm:
        auto_mapping: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


bunny:
    host:     "%rabbit_url%"           # default: 127.0.0.1
    port:     "%rabbit_port%"          # default: 5672
    vhost:    "%rabbit_vhost%"         # default: /
    user:     "%rabbit_user%"          # default: guest
    password: "%rabbit_password%"      # default: guest

    # make heartbeat as long as longest message processing time in any consumer might take
    heartbeat: 120 # in seconds = 2 minutes, default: 60 seconds

    exchanges:
      gateway_exchange:
        durable: true
        type: topic

      necktie_exchange:
        durable: false
        type: direct

    queues:
      queue_gateway:
        durable: false
        bindings:
          - exchange: gateway_exchange

      queue_necktie:
        durable: true
        bindings:
          - exchange: necktie_exchange



services:


