imports:
   - { resource: parameters.yml }
   - { resource: security.yml }
   - { resource: services.yml }

framework:
    secret: "%secret%"
    templating:
        engines: ['twig']

    session:

    router:
        resource: "%kernel.root_dir%/config/routing.yml"


sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    security: { annotations: true }


twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
    orm:
        auto_mapping: true



bunny:
    host:     "%rabbit_url%"           # default: 127.0.0.1
    port:     "%rabbit_port%"          # default: 5672
    vhost:    "%rabbit_vhost%"         # default: /
    user:     "%rabbit_user%"          # default: guest
    password: "%rabbit_password%"      # default: guest

    # make heartbeat as long as longest message processing time in any consumer might take
    heartbeat: 120 # in seconds = 2 minutes, default: 60 seconds

    exchanges:
      gateway_exchange:
        durable: true
        type: topic

      necktie_exchange:
        durable: false
        type: direct

      payment_exchange:
        durable: false
        type: direct

    queues:
      queue_gateway:
        durable: false
        bindings:
          - exchange: gateway_exchange

      queue_necktie:
        durable: true
        bindings:
          - exchange: necktie_exchange

      queue_payment:
          durable: true
          bindings:
            - exchange: payment_exchange

hwi_oauth:

    firewall_names: [secured_area]
    resource_owners:
        necktie:
            type: 'oauth2'
            client_id:         %necktie_public%
            client_secret:     %necktie_secret%
            access_token_url:  %necktie_url%/oauth/v2/token
            authorization_url: %necktie_url%/oauth/v2/auth
            infos_url:         %necktie_url%/api/v1/user
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            options:
              csrf: true
            paths:
              identifier: id
              nickname:   username
              realname:   fullname


services:
