imports:
   - { resource: parameters.yml }

framework:
    secret: "%secret%"
    templating:
            engines: ['twig']

    session:

    router:
        resource: "%kernel.root_dir%/config/routing.yml"


sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    security: { annotations: true }


twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        unix_socket: "/Applications/MAMP/tmp/mysql/mysql.sock"
    orm:
        auto_mapping: true


bunny:
    host:     "%rabbit_url%"           # default: 127.0.0.1
    port:     "%rabbit_port%"          # default: 5672
    vhost:    "%rabbit_vhost%"         # default: /
    user:     "%rabbit_user%"          # default: guest
    password: "%rabbit_password%"      # default: guest

    # make heartbeat as long as longest message processing time in any consumer might take
    heartbeat: 120 # in seconds = 2 minutes, default: 60 seconds

    exchanges:
      gateway_exchange:
        durable: true
        type: fanout

      necktie_exchange:
        durable: false
        type: direct

      payment_exchange:
        durable: false
        type: direct

      payment_redirect_exchange:
        durable: true
        type: fanout

      decrypt_exchange:
        durable: true
        type: fanout

    queues:
      queue_gateway:
        durable: true
        bindings:
          - exchange: gateway_exchange
        arguments:
          x-dead-letter-exchange : 'payment_redirect_exchange' # Exchange used to transfer the message from A to B.

      queue_necktie:
        durable: true
        bindings:
          - exchange: necktie_exchange

      queue_payment:
        durable: true
        bindings:
          - exchange: payment_exchange

      queue_payment_redirect_delay:
        durable: true
        bindings:
          - exchange: payment_redirect_exchange
        arguments:
          x-message-ttl : 30000 # Delay until the message is transferred in milliseconds.
          x-dead-letter-exchange : 'gateway_exchange' # Exchange used to transfer the message from A to B.

      queue_decrypt:
        durable: true
        bindings:
          - exchange: decrypt_exchange

services:
