imports:
   - { resource: parameters.yml }

framework:
    secret: S0ME_SECRET

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        port:     %database_port%
    orm:
        auto_mapping: true


services:


