
gateway:
    path : /
    defaults:  { _controller: GatewayBundle:Home:index }


gateway_restart:
     path : /restart
     defaults:  { _controller: GatewayBundle:Home:restart }


gateway_run:
     path : /run
     defaults:  { _controller: GatewayBundle:Home:run }


payment:
    resource: "@GatewayBundle/Controller"
    type:     annotation