gateway:
    path : /
    defaults:  { _controller: GatewayBundle:Home:index }


gateway_dashboard:
    path : /gw/
    defaults:  { _controller: GatewayBundle:Home:dashboard }


gateway_rabbitmq:
  path: /gw/rabbitmq
  defaults:  { _controller: GatewayBundle:Home:rabbit }


gateway_logger:
  path: /gw/logger
  defaults:  { _controller: GatewayBundle:Home:logger }


gateway_status:
  path: /gw/status
  defaults:  { _controller: GatewayBundle:Home:status }


gateway_stop_all_processes:
  path: /gw/stop-all
  defaults:  { _controller: GatewayBundle:Home:stopAllProcesses }


gateway_start_all_processes:
  path: /gw/start-all
  defaults:  { _controller: GatewayBundle:Home:startAllProcesses }


gateway_supervisor:
  path: /gw/supervisor
  defaults:  { _controller: GatewayBundle:Home:supervisor }


gateway_messages:
  path: /gw/messages
  defaults:  { _controller: GatewayBundle:Home:messages }


gateway_requests:
  path: /gw/requests
  defaults:  { _controller: GatewayBundle:Home:requests }


supervisor_restart:
     path : /gw/restart
     defaults:  { _controller: GatewayBundle:Home:restart }


supervisor_stop_process:
     path : /gw/stop-process/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:stopProcess }


supervisor_start_process:
     path : /gw/start-process/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:startProcess }


supervisor_logs_process:
     path : /gw/process-logs/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:processLogs }


supervisor_clean_log_process:
     path : /gw/process-logs-clean/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:cleanLog }


payment:
    resource: "@GatewayBundle/Controller"
    type:     annotation


driver:
    resource: "@GatewayBundle/Controller"
    type: annotation


hwi_oauth_connect:
  path: /login
  defaults:  { _controller: HWIOAuthBundle:Connect:connect }


hwi_oauth_service_redirect:
  path: /login/{service}
  defaults: { _controller: HWIOAuthBundle:Connect:redirectToService }


hwi_oauth_connect_registration:
  path: /registration/{key}
  defaults: { _controller: HWIOAuthBundle:Connect:registration }


necktie:
    path: /login/check-necktie