
gateway:
    path : /
    defaults:  { _controller: GatewayBundle:Home:index }


gateway_rabbitmq:
  path: /rabbitmq
  defaults:  { _controller: GatewayBundle:Home:rabbit }


gateway_supervisor:
  path: /supervisor
  defaults:  { _controller: GatewayBundle:Home:supervisor }


gateway_logs:
  path: /logs
  defaults:  { _controller: GatewayBundle:Home:logs }


supervisor_restart:
     path : /restart
     defaults:  { _controller: GatewayBundle:Home:restart }


supervisor_stop_process:
     path : /stop-process/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:stopProcess }


supervisor_start_process:
     path : /start-process/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:startProcess }


supervisor_logs_process:
     path : /process-logs/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:processLogs }


supervisor_clean_log_process:
     path : /process-logs-clean/{group}/{name}
     defaults:  { _controller: GatewayBundle:Home:cleanLog }

gateway_run:
     path : /run
     defaults:  { _controller: GatewayBundle:Home:run }


payment:
    resource: "@GatewayBundle/Controller"
    type:     annotation