security:

  providers:
      oAuth:
        id: gw.user_provider

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER


  firewalls:
      secured_area:

      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

