security:

  providers:
      oAuth:
        id: gw.user_provider

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER


  firewalls:
      secured_area:
        anonymous: ~
        logout:
            path:   /logout
            target: /
        oauth:
            resource_owners:
                necktie:  "/login/check-necktie"
            login_path:   /login
            use_forward:  false
            failure_path: /login
            always_use_default_target_path: true
            default_target_path: /gw

            oauth_user_provider:
                service: gw.user_provider
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false


  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/gw, roles: ROLE_USER }