services:

  necktie.gateway.logger:
    class: Necktie\Bundle\GatewayBundle\Logger\Logger


  necktie.client.factory:
    class: Necktie\Bundle\GatewayBundle\Gateway\ClientFactory


  necktie.gateway.api_gateway:
    class: Necktie\Bundle\GatewayBundle\Gateway\ApiGateway
    arguments:
       - "@necktie.client.factory"


  necktie.sender:
    class: Necktie\Bundle\GatewayBundle\NecktieSender
    arguments: ["%necktie_url%", "%necktie_api%"]


  necktie.listener.message_processor:
     class: Necktie\Bundle\GatewayBundle\EventListener\MessageProcessor
     arguments:
        - "@necktie.gateway.api_gateway"
        - "@necktie.producer"
        - "@necktie.gateway.logger"
     tags:
         - { name: doctrine.event_listener, event: postPersist, priority: 2048 }


  necktie.producer:
    class: Necktie\Bundle\GatewayBundle\Producer\Producer
    arguments:
      - "@necktie.bunny.client"

